services:
  - type: web
    name: voltservers
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: voltservers-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /api/health

databases:
  - name: voltservers-db
    databaseName: voltservers
    user: voltservers